language: android

android:
  components:
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
    - build-tools-20.0.0
    - build-tools-22.0.0
    - platform-tools
    - tools
    - android-22
    - sys-img-armeabi-v7a-android-21
    - android-16
  licenses:
    - '.+'

notifications:
  email:
    recipients:
      - harshapaul.pinto@v2solutions.com
    on_success: always
    on_failure: always

#Give appropriate rights to the respective scripts.
before_install:
    - chmod +x gradlew

script:
    #Default Value for APP_BUILD_ENV
  - APP_BUILD_ENV=DEV

  - if [ "$TRAVIS_BRANCH" = "develop" ]; then
        echo "develop Scheme Selected.";
        TERM=dumb ./gradlew assembleDEVRelease;
    elif [ "$TRAVIS_BRANCH" = "QA" ]; then
        APP_BUILD_ENV=QA;
        echo "QA Scheme Selected.";
        TERM=dumb ./gradlew assembleQARelease;
    elif [ "$TRAVIS_BRANCH" = "master" ]; then
        APP_BUILD_ENV=UAT;
        echo "master Scheme Selected.";
        TERM=dumb ./gradlew assembleUATRelease;
    fi


